theme: jekyll-theme-dinky

integration_spreadsheet_key: 2PACX-1vQtek8YO0ig5vXNV5Cz8pupiKNO3ZBV8qL0K6h97l65flW08-rLnQtQb__jFO5X-9Q_kczycVkQ-O0S

github_user: hannahspero
github_repo: LandslideTriggeredTsunamis
